.TH CSB "1" "January 2010"
.SH NAME
csb \- curses sql browser
.SH SYNOPSIS
.B csb
[\fIOPTIONS\fR] [DATABASE URI]
.SH DESCRIPTION
.\" Add any additional description here
.PP
Views tables in SQL databases and allows them to be edited
.TP
\fB\-\-help\fR
display this help and exit
.TP
\fB\-\-version\fR
output version information and exit
.TP
\fB\-\-table [TABLE]\fR
view the specified table by default
.TP
\fB\-\-debug\fR
log activity details to csb.log
.TP
\fB\-\-yes\fR
don't ask for confirmation when modifying data
.SH AUTHOR
Written by Shish
.SH COPYRIGHT
Copyright \(co 2010 Shish
License GPLv2: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
